//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.3

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Copy, Clone, Default, Debug, DeriveEntity)]
pub struct Entity;

impl EntityName for Entity {
    fn table_name(&self) -> &str {
        "network_token"
    }
}

#[derive(Clone, Debug, PartialEq, DeriveModel, DeriveActiveModel, Eq, Serialize, Deserialize)]
pub struct Model {
    pub token: String,
    pub network_id: i64,
    pub create_at: Option<DateTime>,
    pub disabled: bool,
    pub id: i64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveColumn)]
pub enum Column {
    Token,
    NetworkId,
    CreateAt,
    Disabled,
    Id,
}

#[derive(Copy, Clone, Debug, EnumIter, DerivePrimaryKey)]
pub enum PrimaryKey {
    Id,
}

impl PrimaryKeyTrait for PrimaryKey {
    type ValueType = i64;
    fn auto_increment() -> bool {
        false
    }
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {
    Network
}

impl ColumnTrait for Column {
    type EntityName = Entity;
    fn def(&self) -> ColumnDef {
        match self {
            Self::Token => ColumnType::Text.def(),
            Self::NetworkId => ColumnType::BigInteger.def(),
            Self::CreateAt => ColumnType::DateTime.def().null(),
            Self::Disabled => ColumnType::Boolean.def(),
            Self::Id => ColumnType::BigInteger.def(),
        }
    }
}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        match Relation::Network {
            Relation::Network => {
                Entity::belongs_to(super::network::Entity)
                    .from(Column::NetworkId)
                    .to(super::network::Column::NetworkId)
                    .into()
            }
        }
    }
}

impl ActiveModelBehavior for ActiveModel {}

impl Related<super::network::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Network.def()
    }
}

